import { useEffect, useState } from 'react';
import { api } from '../api';

const SCHEDULES = ['manual', 'daily', 'weekly'];

const EXAMPLE_TEMPLATES = [
  {
    name: 'Daily Standup',
    template:
      'Standup {date}:\n- Yesterday: \n- Today: \n- Blockers: \n\nGenerated by DeepFocus (run #{run_count})',
    schedule: 'daily',
  },
  {
    name: 'Weekly Report',
    template:
      'Weekly Report — Week of {date}\n\nCompleted tasks: \nFocus hours: \nKey wins: \n\nRun #{run_count}',
    schedule: 'weekly',
  },
  {
    name: 'Email Follow-up',
    template:
      'Subject: Follow-up — {date}\n\nHi,\n\nFollowing up on our conversation. Please let me know if you have any questions.\n\nBest,\n[Your name]',
    schedule: 'manual',
  },
];

export default function Automations() {
  const [automations, setAutomations] = useState([]);
  const [showForm, setShowForm] = useState(false);
  const [lastOutput, setLastOutput] = useState(null);
  const [form, setForm] = useState({
    name: '',
    description: '',
    template: '',
    schedule: 'manual',
  });

  function loadAutomations() {
    api.getAutomations().then(setAutomations).catch(console.error);
  }

  useEffect(() => {
    loadAutomations();
  }, []);

  async function handleCreate(e) {
    e.preventDefault();
    if (!form.name.trim() || !form.template.trim()) return;
    try {
      await api.createAutomation(form);
      setForm({ name: '', description: '', template: '', schedule: 'manual' });
      setShowForm(false);
      loadAutomations();
    } catch (err) {
      console.error(err);
    }
  }

  async function handleRun(id) {
    try {
      const result = await api.runAutomation(id);
      setLastOutput(result);
      loadAutomations();
    } catch (err) {
      console.error(err);
    }
  }

  async function handleToggle(id, isActive) {
    try {
      await api.updateAutomation(id, { is_active: !isActive });
      loadAutomations();
    } catch (err) {
      console.error(err);
    }
  }

  async function handleDelete(id) {
    try {
      await api.deleteAutomation(id);
      loadAutomations();
    } catch (err) {
      console.error(err);
    }
  }

  function useExample(example) {
    setForm({
      name: example.name,
      description: `Template for ${example.name.toLowerCase()}`,
      template: example.template,
      schedule: example.schedule,
    });
    setShowForm(true);
  }

  return (
    <div className="space-y-8">
      <header className="flex items-center justify-between">
        <div>
          <h2 className="text-3xl font-bold tracking-tight">Automations</h2>
          <p className="mt-1 text-white/50">
            Automate repetitive tasks with templates — standups, reports, follow-ups.
          </p>
        </div>
        <button onClick={() => setShowForm(!showForm)} className="btn-primary">
          {showForm ? 'Cancel' : '+ New Automation'}
        </button>
      </header>

      <div className="card">
        <h3 className="text-sm font-medium text-white/70">Template variables</h3>
        <div className="mt-2 flex flex-wrap gap-2">
          {['{date}', '{time}', '{datetime}', '{name}', '{run_count}', '{day}'].map((v) => (
            <code
              key={v}
              className="rounded-lg bg-white/5 px-2 py-1 text-xs text-brand-300"
            >
              {v}
            </code>
          ))}
        </div>
      </div>

      {showForm && (
        <form onSubmit={handleCreate} className="card space-y-4">
          <input
            className="input"
            placeholder="Automation name"
            value={form.name}
            onChange={(e) => setForm({ ...form, name: e.target.value })}
            autoFocus
          />
          <input
            className="input"
            placeholder="Description (optional)"
            value={form.description}
            onChange={(e) => setForm({ ...form, description: e.target.value })}
          />
          <textarea
            className="input min-h-[160px] resize-none font-mono text-sm"
            placeholder="Template text with {variables}..."
            value={form.template}
            onChange={(e) => setForm({ ...form, template: e.target.value })}
          />
          <select
            className="input"
            value={form.schedule}
            onChange={(e) => setForm({ ...form, schedule: e.target.value })}
          >
            {SCHEDULES.map((s) => (
              <option key={s} value={s}>
                {s.charAt(0).toUpperCase() + s.slice(1)}
              </option>
            ))}
          </select>
          <button type="submit" className="btn-primary">
            Create Automation
          </button>
        </form>
      )}

      {!showForm && (
        <div className="card">
          <h3 className="text-sm font-medium text-white/70">Quick start templates</h3>
          <div className="mt-3 flex flex-wrap gap-2">
            {EXAMPLE_TEMPLATES.map((ex) => (
              <button
                key={ex.name}
                onClick={() => useExample(ex)}
                className="rounded-xl border border-white/10 bg-white/5 px-4 py-2 text-sm transition hover:border-violet-500/30 hover:bg-violet-500/10"
              >
                {ex.name}
              </button>
            ))}
          </div>
        </div>
      )}

      {lastOutput && (
        <div className="card border-emerald-500/30 bg-emerald-500/5">
          <div className="flex items-center justify-between">
            <h3 className="font-medium text-emerald-300">Last run output</h3>
            <button
              onClick={() => navigator.clipboard.writeText(lastOutput.output)}
              className="text-xs text-emerald-400 hover:underline"
            >
              Copy to clipboard
            </button>
          </div>
          <pre className="mt-3 whitespace-pre-wrap rounded-xl bg-black/30 p-4 text-sm text-white/80">
            {lastOutput.output}
          </pre>
        </div>
      )}

      <div className="space-y-3">
        {automations.length === 0 ? (
          <div className="card py-12 text-center text-white/40">
            No automations yet. Create one to handle repetitive work automatically.
          </div>
        ) : (
          automations.map((auto) => (
            <div
              key={auto.id}
              className={`card transition ${!auto.is_active ? 'opacity-50' : ''}`}
            >
              <div className="flex items-start justify-between gap-4">
                <div className="flex-1">
                  <div className="flex items-center gap-2">
                    <h3 className="font-medium">{auto.name}</h3>
                    <span className="rounded-full bg-violet-500/20 px-2 py-0.5 text-xs text-violet-300">
                      {auto.schedule}
                    </span>
                    {!auto.is_active && (
                      <span className="rounded-full bg-white/10 px-2 py-0.5 text-xs text-white/40">
                        paused
                      </span>
                    )}
                  </div>
                  {auto.description && (
                    <p className="mt-1 text-sm text-white/50">{auto.description}</p>
                  )}
                  <p className="mt-2 text-xs text-white/30">
                    Runs: {auto.run_count}
                    {auto.last_run_at &&
                      ` · Last: ${new Date(auto.last_run_at).toLocaleString()}`}
                  </p>
                </div>

                <div className="flex items-center gap-2">
                  <button
                    onClick={() => handleRun(auto.id)}
                    disabled={!auto.is_active}
                    className="btn-primary text-sm disabled:opacity-40"
                  >
                    Run
                  </button>
                  <button
                    onClick={() => handleToggle(auto.id, auto.is_active)}
                    className="btn-secondary text-sm"
                  >
                    {auto.is_active ? 'Pause' : 'Enable'}
                  </button>
                  <button
                    onClick={() => handleDelete(auto.id)}
                    className="rounded-lg px-2 py-1.5 text-xs text-red-400/70 transition hover:bg-red-500/10"
                  >
                    Delete
                  </button>
                </div>
              </div>
            </div>
          ))
        )}
      </div>
    </div>
  );
}
